# Phase 2: Istiod Application with Private Registry
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: "1.28.0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  sources:
    # IMPORTANT: Git repo with ref MUST come first for $values to work
    - repoURL: https://github.com/YOUR_ORG/istio-gitops.git
      targetRevision: main
      ref: values
    # Private OCI registry for Helm charts
    - repoURL: oci://your-registry.example.com/helm-charts
      chart: istiod
      targetRevision: "1.28.0"
      helm:
        valueFiles:
          - $values/helm-values/istiod-values.yaml
        # Override to use private image registry
        values: |
          global:
            hub: your-registry.example.com/istio
            tag: "1.28.0"
            imagePullSecrets:
              - name: registry-credentials
  # Ignore webhook caBundle differences (auto-populated by Istio)
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
