{{- if .Values.httpRedirect.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRedirect.name | default "http-to-https-redirect" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy-gateway-wrapper.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | default "envoy-gateway" }}
      namespace: {{ .Release.Namespace }}
      sectionName: http
  {{- if .Values.httpRedirect.hostnames }}
  hostnames:
    {{- toYaml .Values.httpRedirect.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: {{ .Values.httpRedirect.statusCode | default 301 }}
{{- end }}
