{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy-gateway-config.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- with .hostname }}
      hostname: {{ . | quote }}
      {{- end }}
      {{- with .tls }}
      tls:
        mode: {{ .mode }}
        certificateRefs:
          {{- toYaml .certificateRefs | nindent 10 }}
      {{- end }}
      allowedRoutes:
        {{- toYaml .allowedRoutes | nindent 8 }}
    {{- end }}
{{- end }}
