apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wwwz-wiz
  labels:
    app.kubernetes.io/name: wwwz
    app.kubernetes.io/component: report
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vaultStore.name | quote }}
    kind: {{ .Values.vaultStore.kind | quote }}
  target:
    name: wwwz-wiz
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WIZ_CLIENT_ID: "{{ `{{ .client_id }}` }}"
        WIZ_CLIENT_SECRET: "{{ `{{ .client_secret }}` }}"
        {{- if .Values.teamsWebhook.enabled }}
        TEAMS_WEBHOOK_URL: "{{ `{{ .teams_webhook_url }}` }}"
        {{- end }}
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.vaultPath | quote }}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.vaultPath | quote }}
        property: client_secret
    {{- if .Values.teamsWebhook.enabled }}
    - secretKey: teams_webhook_url
      remoteRef:
        key: {{ .Values.vaultPath | quote }}
        property: teams_webhook_url
    {{- end }}
