apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwz-output
  labels:
    app.kubernetes.io/name: wwwz
    app.kubernetes.io/component: report
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
  {{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass | quote }}
  {{- end }}
