apiVersion: v1
kind: Secret
metadata:
  name: wwwz-viewer-auth
  labels:
    app.kubernetes.io/name: wwwz
    app.kubernetes.io/component: viewer
type: Opaque
stringData:
  htpasswd: |
    {{ .Values.htpasswd }}
