apiVersion: v1
kind: Service
metadata:
  name: wwwz-viewer
  labels:
    app.kubernetes.io/name: wwwz
    app.kubernetes.io/component: viewer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wwwz
    app.kubernetes.io/component: viewer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
